image: docker:20.10.16
services:
    - docker:20.10.16-dind
stages:
    - build
    - test
    - release
    - deploy
variables:
    CONTAINER_TEST_IMAGE: $CI_REGISTRY_TEST:$CI_COMMIT_REF_SLUG
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest
before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
build:
    stage: build
    script:
        - docker build -t $CONTAINER_TEST_IMAGE .
        - docker push $CONTAINER_TEST_IMAGE
test:
    stage: test
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker run $CONTAINER_TEST_IMAGE npm test
release-image:
    stage: release
    script:
        - docker pull $CONTAINER_TEST_IMAGE
        - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
        - docker push $CONTAINER_RELEASE_IMAGE
deploy-server:
    stage: deploy
    tags:
        - local_docker
    script:
        - docker pull $CONTAINER_RELEASE_IMAGE
