image: docker:20.10.16
stages:
    - build
    - deploy
variables:
    CONTAINER_RELEASE_IMAGE: $CI_REGISTRY/qm-h/webapp-devops:latest
before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
build:
    stage: build
    tags: 
        - build
    script:
        - docker build --no-cache -t $CONTAINER_RELEASE_IMAGE .
        - docker push $CONTAINER_RELEASE_IMAGE
deploy:
    stage: deploy
    tags: 
        - deploy
    script:
        - docker pull $CONTAINER_RELEASE_IMAGE
        - docker run -d -p 8080:8080 $CONTAINER_RELEASE_IMAGE
