stages:
    - containerization
    - deploy
services:
  - docker:dind
containerization:
    stage: containerization # must match the stage name declared above
    script:
        # Build the container image
        - docker build -t webapp-devops .
        # Push the container image to the registry
        - docker push webapp-devops
        # Cleanup by removing the local image
        - docker image rm webapp-devops
deployment:
    stage: deploy # must match the stage name declared above
    script:
        # create/update the kubernetes resources
        - kubectl apply -f kubernetes_manifest.yml
        # Restart the deployment so as to pull the latest version of the container image
        - kubectl rollout restart deployment/webapp-devops
    environment:
        name: production
