export const avatar = [
    'https://img.icons8.com/emoji/344/hippopotamus-emoji.png',
    'https://img.icons8.com/emoji/344/raccoon.png',
    'https://img.icons8.com/emoji/344/wolf-emoji.png',
    'https://img.icons8.com/emoji/344/tiger-face.png',
    'https://img.icons8.com/emoji/344/turtle-emoji.png',
    'https://img.icons8.com/emoji/344/sloth-emoji.png',
    'https://img.icons8.com/emoji/344/llama-emoji.png',
    'https://img.icons8.com/emoji/344/cat-face--v1.png',
    'https://img.icons8.com/color/344/ninja-turtle.png',
    'https://img.icons8.com/color/344/grinch.png',
    'https://img.icons8.com/color/344/tanjiro-kamado.png',
    'https://img.icons8.com/color/344/stitch-character.png',
    'https://img.icons8.com/color/344/jake--v1.png',
    'https://img.icons8.com/color/344/the-flash-head.png',
    'https://img.icons8.com/color/344/futurama-bender--v1.png',
    'https://img.icons8.com/color/344/futurama-fry.png',
    'https://img.icons8.com/color/344/batman.png',
    'https://img.icons8.com/color/344/joker-dc.png',
    'https://img.icons8.com/color/344/sonic-the-hedgehog-1.png',
    'https://img.icons8.com/color/344/super-mario.png',
    'https://img.icons8.com/color/344/spyro.png',
    'https://img.icons8.com/color/344/luigi.png',
    'https://img.icons8.com/color/344/Eggman-robotnik.png',
    'https://img.icons8.com/color/344/spiderman-head.png',
    'https://img.icons8.com/color/344/iron-man.png',
    'https://img.icons8.com/color/344/avatar.png',
    'https://img.icons8.com/color/344/john-wick.png',
    'https://img.icons8.com/color/344/gremlin2.png',
    'https://img.icons8.com/color/344/dobby.png',
    'https://img.icons8.com/color/344/harry-potter-.png',
    'https://img.icons8.com/color/344/walter-white.png',
    'https://img.icons8.com/color/344/darth-vader.png',
    'https://img.icons8.com/color/344/stormtrooper.png',
    'https://img.icons8.com/color/344/c-3po.png',
    'https://img.icons8.com/color/344/baby-yoda.png',
    'https://img.icons8.com/color/344/luke-skywalker.png',
    'https://img.icons8.com/color/344/mando.png',
    'https://img.icons8.com/color/344/r2-d2.png',
    'https://img.icons8.com/color/344/yoda.png',
    'https://img.icons8.com/color/344/siba-inu-kawaii.png',
    'https://img.icons8.com/color/344/finn--v1.png',
    'https://img.icons8.com/color/344/stan-marsh.png',
    'https://img.icons8.com/color/344/eric-cartman.png',
    'https://img.icons8.com/color/344/kyle-broflovski.png',
    'https://img.icons8.com/color/344/kenny-mccormick.png',
    'https://img.icons8.com/color/344/morpheus.png',
    'https://img.icons8.com/color/344/neo.png',
    'https://img.icons8.com/color/344/trinity.png',
    'https://img.icons8.com/color/344/agent-smith.png',
    'https://img.icons8.com/color/344/homer-simpson--v1.png ',
]
export const randomAvatar = (): string => {
    const randomIndex = Math.floor(Math.random() * avatar.length)
    return avatar[randomIndex]
}
